// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VVortex.h for the primary calling header

#ifndef VERILATED_VVORTEX_VX_FPU_DPI__N4_T1_O3_H_
#define VERILATED_VVORTEX_VX_FPU_DPI__N4_T1_O3_H_  // guard

#include "verilated.h"

class VVortex__Syms;

class VVortex_VX_fpu_dpi__N4_T1_O3 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__reset,0,0);
        VL_IN8(__PVT__valid_in,0,0);
        VL_OUT8(__PVT__ready_in,0,0);
        VL_IN8(__PVT__lane_mask,3,0);
        VL_IN8(__PVT__tag_in,0,0);
        VL_IN8(__PVT__op_type,3,0);
        VL_IN8(__PVT__fmt,1,0);
        VL_IN8(__PVT__frm,2,0);
        VL_OUT8(__PVT__has_fflags,0,0);
        VL_OUT8(__PVT__fflags,4,0);
        VL_OUT8(__PVT__tag_out,0,0);
        VL_IN8(__PVT__ready_out,0,0);
        VL_OUT8(__PVT__valid_out,0,0);
        CData/*3:0*/ __PVT__per_core_ready_in;
        CData/*3:0*/ __PVT__per_core_tag_out;
        CData/*3:0*/ __PVT__per_core_ready_out;
        CData/*3:0*/ __PVT__per_core_valid_out;
        CData/*3:0*/ __PVT__per_core_has_fflags;
        IData/*19:0*/ __PVT__per_core_fflags;
        CData/*1:0*/ __PVT__core_select;
        CData/*0:0*/ __PVT__is_fadd;
        CData/*0:0*/ __PVT__is_fsub;
        CData/*0:0*/ __PVT__is_fmul;
        CData/*0:0*/ __PVT__is_fmadd;
        CData/*0:0*/ __PVT__is_fmsub;
        CData/*0:0*/ __PVT__is_fnmadd;
        CData/*0:0*/ __PVT__is_fnmsub;
        CData/*0:0*/ __PVT__is_div;
        CData/*0:0*/ __PVT__is_fcmp;
        CData/*0:0*/ __PVT__is_itof;
        CData/*0:0*/ __PVT__is_utof;
        CData/*0:0*/ __PVT__is_ftoi;
        CData/*0:0*/ __PVT__is_ftou;
        CData/*0:0*/ __PVT__is_f2f;
        CData/*0:0*/ __PVT__dst_fmt;
        CData/*0:0*/ __PVT__int_fmt;
        CData/*1:0*/ __Vcellout__div_sqrt_arb__ready_in;
        CData/*1:0*/ __Vcellinp__div_sqrt_arb__valid_in;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fma;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fadd;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fsub;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fmul;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fmadd;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fmsub;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fnmadd;
        IData/*19:0*/ __PVT__fma__DOT__fflags_fnmsub;
        CData/*0:0*/ __PVT__fma__DOT__fma_valid;
        CData/*0:0*/ __PVT__fma__DOT__fma_ready;
        CData/*0:0*/ __PVT__fma__DOT__fma_fire;
        CData/*4:0*/ __PVT__fma__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__fdiv__DOT__fflags_fdiv;
        CData/*0:0*/ __PVT__fdiv__DOT__fdiv_valid;
        CData/*0:0*/ __PVT__fdiv__DOT__fdiv_ready;
        CData/*0:0*/ __PVT__fdiv__DOT__fdiv_fire;
        CData/*4:0*/ __PVT__fdiv__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__fsqrt__DOT__fflags_fsqrt;
        CData/*0:0*/ __PVT__fsqrt__DOT__fsqrt_valid;
        CData/*0:0*/ __PVT__fsqrt__DOT__fsqrt_ready;
        CData/*0:0*/ __PVT__fsqrt__DOT__fsqrt_fire;
        CData/*4:0*/ __PVT__fsqrt__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__fcvt__DOT__fflags_fcvt;
        IData/*19:0*/ __PVT__fcvt__DOT__fflags_itof;
        IData/*19:0*/ __PVT__fcvt__DOT__fflags_utof;
    };
    struct {
        IData/*19:0*/ __PVT__fcvt__DOT__fflags_ftoi;
        IData/*19:0*/ __PVT__fcvt__DOT__fflags_ftou;
        CData/*0:0*/ __PVT__fcvt__DOT__fcvt_valid;
        CData/*0:0*/ __PVT__fcvt__DOT__fcvt_ready;
        CData/*0:0*/ __PVT__fcvt__DOT__fcvt_fire;
        CData/*4:0*/ __PVT__fcvt__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__fncp__DOT__fflags_fncp;
        IData/*19:0*/ __PVT__fncp__DOT__fflags_flt;
        IData/*19:0*/ __PVT__fncp__DOT__fflags_fle;
        IData/*19:0*/ __PVT__fncp__DOT__fflags_feq;
        IData/*19:0*/ __PVT__fncp__DOT__fflags_fmin;
        IData/*19:0*/ __PVT__fncp__DOT__fflags_fmax;
        CData/*0:0*/ __PVT__fncp__DOT__fncp_valid;
        CData/*0:0*/ __PVT__fncp__DOT__fncp_ready;
        CData/*0:0*/ __PVT__fncp__DOT__fncp_fire;
        CData/*4:0*/ __PVT__fncp__DOT_____05Ffflags_merged;
        CData/*4:0*/ __Vlvbound_h41c8a5b5__0;
        CData/*4:0*/ __Vlvbound_hc3f8bfe1__0;
        CData/*4:0*/ __Vlvbound_h49eb26c4__0;
        CData/*4:0*/ __Vlvbound_h147cf4e8__0;
        CData/*4:0*/ __Vlvbound_h71951e49__0;
        CData/*4:0*/ __Vlvbound_h01b131d5__0;
        CData/*4:0*/ __Vlvbound_hacab2bfc__0;
        CData/*4:0*/ __Vlvbound_h198ed5c2__0;
        CData/*4:0*/ __Vlvbound_h8d23a7ba__0;
        CData/*4:0*/ __Vlvbound_h790a2257__0;
        CData/*4:0*/ __Vlvbound_ha816653d__0;
        CData/*4:0*/ __Vlvbound_h24bf1863__0;
        CData/*4:0*/ __Vlvbound_h8d4e7366__0;
        CData/*4:0*/ __Vlvbound_h6ce28c5f__0;
        CData/*4:0*/ __Vlvbound_h268775a1__0;
        CData/*4:0*/ __Vlvbound_hc8074bd5__0;
        CData/*4:0*/ __Vlvbound_h876b3e60__0;
        CData/*4:0*/ __Vlvbound_hf8131c8b__0;
        CData/*4:0*/ __Vlvbound_h63cd8b65__0;
        CData/*4:0*/ __Vlvbound_h82db57c2__0;
        CData/*4:0*/ __Vlvbound_h98d9d482__0;
        CData/*4:0*/ __Vlvbound_h98d9d482__1;
        CData/*4:0*/ __Vlvbound_h98d9d482__2;
        CData/*4:0*/ __Vlvbound_h98d9d482__3;
        CData/*4:0*/ __Vlvbound_h98d9d482__4;
        CData/*0:0*/ __PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_index_r;
        CData/*1:0*/ __PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_onehot_r;
        CData/*0:0*/ __PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__state;
        CData/*1:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_index_r;
        CData/*3:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_onehot_r;
        CData/*1:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__state;
        CData/*0:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__valid_out_r;
        CData/*0:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__use_buffer;
        CData/*0:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__stall_out;
        CData/*0:0*/ fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__1;
        CData/*0:0*/ fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__0;
        CData/*0:0*/ fma__DOT__shift_reg__DOT____Vlvbound_h4cd7645a__0;
        CData/*0:0*/ fma__DOT__shift_reg__DOT____Vlvbound_h3fda9eff__0;
        CData/*0:0*/ fma__DOT__shift_reg__DOT____Vlvbound_h51e46508__0;
        CData/*0:0*/ fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__1;
        CData/*0:0*/ fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__0;
        CData/*0:0*/ fdiv__DOT__shift_reg__DOT____Vlvbound_h790d5d4e__0;
        CData/*0:0*/ fdiv__DOT__shift_reg__DOT____Vlvbound_h0c1ea029__0;
        CData/*0:0*/ fdiv__DOT__shift_reg__DOT____Vlvbound_h7e234417__0;
        CData/*0:0*/ fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1;
        CData/*0:0*/ fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0;
        CData/*0:0*/ fsqrt__DOT__shift_reg__DOT____Vlvbound_h2627712a__0;
        CData/*0:0*/ fsqrt__DOT__shift_reg__DOT____Vlvbound_h94c3c44b__0;
    };
    struct {
        CData/*0:0*/ fsqrt__DOT__shift_reg__DOT____Vlvbound_hf588c92f__0;
        CData/*0:0*/ fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1;
        CData/*0:0*/ fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0;
        CData/*0:0*/ fcvt__DOT__shift_reg__DOT____Vlvbound_h6d835738__0;
        CData/*0:0*/ fcvt__DOT__shift_reg__DOT____Vlvbound_h784a533e__0;
        CData/*0:0*/ fcvt__DOT__shift_reg__DOT____Vlvbound_hf606f480__0;
        CData/*0:0*/ fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__1;
        CData/*0:0*/ fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__0;
        CData/*0:0*/ fncp__DOT__shift_reg__DOT____Vlvbound_hb3b562d1__0;
        CData/*0:0*/ fncp__DOT__shift_reg__DOT____Vlvbound_h0fa13e82__0;
        CData/*0:0*/ fncp__DOT__shift_reg__DOT____Vlvbound_hba509cd1__0;
        CData/*4:0*/ __Vtask_dpi_fadd__0__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__1__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__2__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__3__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__4__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__5__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__6__fflags;
        CData/*4:0*/ __Vtask_dpi_fdiv__7__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__8__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__9__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__10__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__11__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__12__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__15__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__16__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__17__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__18__fflags;
        CData/*4:0*/ __Vtask_dpi_fmax__19__fflags;
        CData/*4:0*/ __Vtask_dpi_fadd__23__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__24__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__25__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__26__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__27__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__28__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__29__fflags;
        CData/*4:0*/ __Vtask_dpi_fdiv__30__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__31__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__32__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__33__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__34__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__35__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__38__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__39__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__40__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__41__fflags;
        CData/*4:0*/ __Vtask_dpi_fmax__42__fflags;
        CData/*4:0*/ __Vtask_dpi_fadd__46__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__47__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__48__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__49__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__50__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__51__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__52__fflags;
        CData/*4:0*/ __Vtask_dpi_fdiv__53__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__54__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__55__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__56__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__57__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__58__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__61__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__62__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__63__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__64__fflags;
    };
    struct {
        CData/*4:0*/ __Vtask_dpi_fmax__65__fflags;
        CData/*4:0*/ __Vtask_dpi_fadd__69__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__70__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__71__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__72__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__73__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__74__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__75__fflags;
        CData/*4:0*/ __Vtask_dpi_fdiv__76__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__77__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__78__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__79__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__80__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__81__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__84__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__85__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__86__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__87__fflags;
        CData/*4:0*/ __Vtask_dpi_fmax__88__fflags;
        CData/*3:0*/ __Vtableidx1;
        CData/*5:0*/ __Vtableidx2;
        CData/*3:0*/ __Vtableidx3;
        CData/*5:0*/ __Vtableidx4;
        CData/*3:0*/ __Vtableidx5;
        CData/*5:0*/ __Vtableidx6;
        CData/*3:0*/ __Vtableidx7;
        CData/*5:0*/ __Vtableidx8;
        CData/*0:0*/ __Vdly__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__valid_out_r;
        IData/*19:0*/ __Vxrand_h9763b5f5__0;
        VlWide<4>/*127:0*/ __Vxrand_hdbee654f__0;
        VL_INW(__PVT__dataa,127,0,4);
        VL_INW(__PVT__datab,127,0,4);
        VL_INW(__PVT__datac,127,0,4);
        VL_OUTW(__PVT__result,127,0,4);
        VlWide<16>/*511:0*/ __PVT__per_core_result;
        VlWide<17>/*539:0*/ __PVT__per_core_data_out;
        VlWide<4>/*127:0*/ __PVT__fma__DOT__result_fma;
        VlWide<4>/*127:0*/ __PVT__fdiv__DOT__result_fdiv_r;
        VlWide<4>/*127:0*/ __PVT__fsqrt__DOT__result_fsqrt_r;
        VlWide<4>/*127:0*/ __PVT__fcvt__DOT__result_fcvt;
        VlWide<4>/*127:0*/ __PVT__fncp__DOT__result_fncp;
        VlWide<5>/*134:0*/ div_sqrt_arb__DOT____Vxrand_h3a5e75a1__0;
        VlWide<5>/*135:0*/ div_sqrt_arb__DOT____Vcellinp__genblk1__DOT__genblk1__DOT__out_buf__data_in;
        VlWide<5>/*134:0*/ rsp_arb__DOT____Vxrand_h3a5e75a1__0;
        VlWide<5>/*136:0*/ rsp_arb__DOT____Vcellinp__genblk1__DOT__genblk1__DOT__out_buf__data_in;
        VlWide<5>/*136:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__data_out_r;
        VlWide<5>/*136:0*/ __PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__buffer;
        VlWide<17>/*539:0*/ __PVT__fma__DOT__shift_reg__DOT__genblk1__DOT__entries;
        VlWide<64>/*2024:0*/ __PVT__fdiv__DOT__shift_reg__DOT__genblk1__DOT__entries;
        VlWide<43>/*1349:0*/ __PVT__fsqrt__DOT__shift_reg__DOT__genblk1__DOT__entries;
        VlWide<22>/*674:0*/ __PVT__fcvt__DOT__shift_reg__DOT__genblk1__DOT__entries;
        VlWide<9>/*271:0*/ __PVT__fncp__DOT__shift_reg__DOT__genblk1__DOT__entries;
        VlWide<8>/*255:0*/ __PVT__fma__DOT__result_fadd;
        VlWide<8>/*255:0*/ __PVT__fma__DOT__result_fsub;
        VlWide<8>/*255:0*/ __PVT__fma__DOT__result_fmul;
        VlWide<8>/*255:0*/ __PVT__fma__DOT__result_fmadd;
        VlWide<8>/*255:0*/ __PVT__fma__DOT__result_fmsub;
        VlWide<8>/*255:0*/ __PVT__fma__DOT__result_fnmadd;
        VlWide<8>/*255:0*/ __PVT__fma__DOT__result_fnmsub;
        VlWide<8>/*255:0*/ __PVT__fdiv__DOT__result_fdiv;
        VlWide<8>/*255:0*/ __PVT__fsqrt__DOT__result_fsqrt;
        VlWide<8>/*255:0*/ __PVT__fcvt__DOT__result_itof;
        VlWide<8>/*255:0*/ __PVT__fcvt__DOT__result_utof;
        VlWide<8>/*255:0*/ __PVT__fcvt__DOT__result_ftoi;
    };
    struct {
        VlWide<8>/*255:0*/ __PVT__fcvt__DOT__result_ftou;
        VlWide<8>/*255:0*/ __PVT__fcvt__DOT__result_f2f;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fclss;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_flt;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fle;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_feq;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fmin;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fmax;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fsgnj;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fsgnjn;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fsgnjx;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fmvx;
        VlWide<8>/*255:0*/ __PVT__fncp__DOT__result_fmvf;
        QData/*63:0*/ __Vtask_dpi_fadd__0__result;
        QData/*63:0*/ __Vtask_dpi_fsub__1__result;
        QData/*63:0*/ __Vtask_dpi_fmul__2__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__3__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__4__result;
        QData/*63:0*/ __Vtask_dpi_fnmadd__5__result;
        QData/*63:0*/ __Vtask_dpi_fnmsub__6__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__7__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__8__result;
        QData/*63:0*/ __Vtask_dpi_itof__9__result;
        QData/*63:0*/ __Vtask_dpi_utof__10__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__11__result;
        QData/*63:0*/ __Vtask_dpi_ftou__12__result;
        QData/*63:0*/ __Vtask_dpi_f2f__13__result;
        QData/*63:0*/ __Vtask_dpi_fclss__14__result;
        QData/*63:0*/ __Vtask_dpi_fle__15__result;
        QData/*63:0*/ __Vtask_dpi_flt__16__result;
        QData/*63:0*/ __Vtask_dpi_feq__17__result;
        QData/*63:0*/ __Vtask_dpi_fmin__18__result;
        QData/*63:0*/ __Vtask_dpi_fmax__19__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__20__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__21__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__22__result;
        QData/*63:0*/ __Vtask_dpi_fadd__23__result;
        QData/*63:0*/ __Vtask_dpi_fsub__24__result;
        QData/*63:0*/ __Vtask_dpi_fmul__25__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__26__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__27__result;
        QData/*63:0*/ __Vtask_dpi_fnmadd__28__result;
        QData/*63:0*/ __Vtask_dpi_fnmsub__29__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__30__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__31__result;
        QData/*63:0*/ __Vtask_dpi_itof__32__result;
        QData/*63:0*/ __Vtask_dpi_utof__33__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__34__result;
        QData/*63:0*/ __Vtask_dpi_ftou__35__result;
        QData/*63:0*/ __Vtask_dpi_f2f__36__result;
        QData/*63:0*/ __Vtask_dpi_fclss__37__result;
        QData/*63:0*/ __Vtask_dpi_fle__38__result;
        QData/*63:0*/ __Vtask_dpi_flt__39__result;
        QData/*63:0*/ __Vtask_dpi_feq__40__result;
        QData/*63:0*/ __Vtask_dpi_fmin__41__result;
        QData/*63:0*/ __Vtask_dpi_fmax__42__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__43__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__44__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__45__result;
        QData/*63:0*/ __Vtask_dpi_fadd__46__result;
        QData/*63:0*/ __Vtask_dpi_fsub__47__result;
        QData/*63:0*/ __Vtask_dpi_fmul__48__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__49__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__50__result;
    };
    struct {
        QData/*63:0*/ __Vtask_dpi_fnmadd__51__result;
        QData/*63:0*/ __Vtask_dpi_fnmsub__52__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__53__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__54__result;
        QData/*63:0*/ __Vtask_dpi_itof__55__result;
        QData/*63:0*/ __Vtask_dpi_utof__56__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__57__result;
        QData/*63:0*/ __Vtask_dpi_ftou__58__result;
        QData/*63:0*/ __Vtask_dpi_f2f__59__result;
        QData/*63:0*/ __Vtask_dpi_fclss__60__result;
        QData/*63:0*/ __Vtask_dpi_fle__61__result;
        QData/*63:0*/ __Vtask_dpi_flt__62__result;
        QData/*63:0*/ __Vtask_dpi_feq__63__result;
        QData/*63:0*/ __Vtask_dpi_fmin__64__result;
        QData/*63:0*/ __Vtask_dpi_fmax__65__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__66__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__67__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__68__result;
        QData/*63:0*/ __Vtask_dpi_fadd__69__result;
        QData/*63:0*/ __Vtask_dpi_fsub__70__result;
        QData/*63:0*/ __Vtask_dpi_fmul__71__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__72__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__73__result;
        QData/*63:0*/ __Vtask_dpi_fnmadd__74__result;
        QData/*63:0*/ __Vtask_dpi_fnmsub__75__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__76__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__77__result;
        QData/*63:0*/ __Vtask_dpi_itof__78__result;
        QData/*63:0*/ __Vtask_dpi_utof__79__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__80__result;
        QData/*63:0*/ __Vtask_dpi_ftou__81__result;
        QData/*63:0*/ __Vtask_dpi_f2f__82__result;
        QData/*63:0*/ __Vtask_dpi_fclss__83__result;
        QData/*63:0*/ __Vtask_dpi_fle__84__result;
        QData/*63:0*/ __Vtask_dpi_flt__85__result;
        QData/*63:0*/ __Vtask_dpi_feq__86__result;
        QData/*63:0*/ __Vtask_dpi_fmin__87__result;
        QData/*63:0*/ __Vtask_dpi_fmax__88__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__89__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__90__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__91__result;
        VlUnpacked<VlWide<8>/*255:0*/, 3> __PVT__operands;
    };

    // INTERNAL VARIABLES
    VVortex__Syms* const vlSymsp;

    // CONSTRUCTORS
    VVortex_VX_fpu_dpi__N4_T1_O3(VVortex__Syms* symsp, const char* name);
    ~VVortex_VX_fpu_dpi__N4_T1_O3();
    VL_UNCOPYABLE(VVortex_VX_fpu_dpi__N4_T1_O3);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
