// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VVortex.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "VVortex_VX_fpu_dpi__N4_T1_O3.h"

VL_ATTR_COLD void VVortex_VX_fpu_dpi__N4_T1_O3___initial__TOP__Vortex__genblk5__BRA__0__KET____DOT__cluster__DOT__genblk4__BRA__0__KET____DOT__socket__DOT__genblk6__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__genblk1__BRA__0__KET____DOT__fpu_dpi__0(VVortex_VX_fpu_dpi__N4_T1_O3* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VVortex__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+                  VVortex_VX_fpu_dpi__N4_T1_O3___initial__TOP__Vortex__genblk5__BRA__0__KET____DOT__cluster__DOT__genblk4__BRA__0__KET____DOT__socket__DOT__genblk6__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__genblk1__BRA__0__KET____DOT__fpu_dpi__0\n"); );
    // Init
    VlWide<5>/*159:0*/ __Vtemp_h34a6e6c0__0;
    VlWide<4>/*127:0*/ __Vtemp_h34a6eee8__0;
    VlWide<5>/*159:0*/ __Vtemp_h34a6e6c0__1;
    // Body
    VL_RAND_RESET_W(135, __Vtemp_h34a6e6c0__0);
    vlSelf->rsp_arb__DOT____Vxrand_h3a5e75a1__0[0U] 
        = __Vtemp_h34a6e6c0__0[0U];
    vlSelf->rsp_arb__DOT____Vxrand_h3a5e75a1__0[1U] 
        = __Vtemp_h34a6e6c0__0[1U];
    vlSelf->rsp_arb__DOT____Vxrand_h3a5e75a1__0[2U] 
        = __Vtemp_h34a6e6c0__0[2U];
    vlSelf->rsp_arb__DOT____Vxrand_h3a5e75a1__0[3U] 
        = __Vtemp_h34a6e6c0__0[3U];
    vlSelf->rsp_arb__DOT____Vxrand_h3a5e75a1__0[4U] 
        = (0x7fU & __Vtemp_h34a6e6c0__0[4U]);
    VL_RAND_RESET_W(128, __Vtemp_h34a6eee8__0);
    vlSelf->__Vxrand_hdbee654f__0[0U] = __Vtemp_h34a6eee8__0[0U];
    vlSelf->__Vxrand_hdbee654f__0[1U] = __Vtemp_h34a6eee8__0[1U];
    vlSelf->__Vxrand_hdbee654f__0[2U] = __Vtemp_h34a6eee8__0[2U];
    vlSelf->__Vxrand_hdbee654f__0[3U] = __Vtemp_h34a6eee8__0[3U];
    vlSelf->__Vxrand_h9763b5f5__0 = (0xfffffU & VL_RAND_RESET_I(20));
    VL_RAND_RESET_W(135, __Vtemp_h34a6e6c0__1);
    vlSelf->div_sqrt_arb__DOT____Vxrand_h3a5e75a1__0[0U] 
        = __Vtemp_h34a6e6c0__1[0U];
    vlSelf->div_sqrt_arb__DOT____Vxrand_h3a5e75a1__0[1U] 
        = __Vtemp_h34a6e6c0__1[1U];
    vlSelf->div_sqrt_arb__DOT____Vxrand_h3a5e75a1__0[2U] 
        = __Vtemp_h34a6e6c0__1[2U];
    vlSelf->div_sqrt_arb__DOT____Vxrand_h3a5e75a1__0[3U] 
        = __Vtemp_h34a6e6c0__1[3U];
    vlSelf->div_sqrt_arb__DOT____Vxrand_h3a5e75a1__0[4U] 
        = (0x7fU & __Vtemp_h34a6e6c0__1[4U]);
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 
        = (1U & VL_RAND_RESET_I(1));
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 
        = (1U & VL_RAND_RESET_I(1));
}

VL_ATTR_COLD void VVortex_VX_fpu_dpi__N4_T1_O3___ctor_var_reset(VVortex_VX_fpu_dpi__N4_T1_O3* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VVortex__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+                  VVortex_VX_fpu_dpi__N4_T1_O3___ctor_var_reset\n"); );
    // Body
    vlSelf->__Vxrand_h9763b5f5__0 = VL_RAND_RESET_I(20);
    VL_RAND_RESET_W(128, vlSelf->__Vxrand_hdbee654f__0);
    vlSelf->__PVT__clk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reset = VL_RAND_RESET_I(1);
    vlSelf->__PVT__valid_in = VL_RAND_RESET_I(1);
    vlSelf->__PVT__ready_in = VL_RAND_RESET_I(1);
    vlSelf->__PVT__lane_mask = VL_RAND_RESET_I(4);
    vlSelf->__PVT__tag_in = VL_RAND_RESET_I(1);
    vlSelf->__PVT__op_type = VL_RAND_RESET_I(4);
    vlSelf->__PVT__fmt = VL_RAND_RESET_I(2);
    vlSelf->__PVT__frm = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(128, vlSelf->__PVT__dataa);
    VL_RAND_RESET_W(128, vlSelf->__PVT__datab);
    VL_RAND_RESET_W(128, vlSelf->__PVT__datac);
    VL_RAND_RESET_W(128, vlSelf->__PVT__result);
    vlSelf->__PVT__has_fflags = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fflags = VL_RAND_RESET_I(5);
    vlSelf->__PVT__tag_out = VL_RAND_RESET_I(1);
    vlSelf->__PVT__ready_out = VL_RAND_RESET_I(1);
    vlSelf->__PVT__valid_out = VL_RAND_RESET_I(1);
    vlSelf->__PVT__per_core_ready_in = VL_RAND_RESET_I(4);
    VL_RAND_RESET_W(512, vlSelf->__PVT__per_core_result);
    vlSelf->__PVT__per_core_tag_out = VL_RAND_RESET_I(4);
    vlSelf->__PVT__per_core_ready_out = VL_RAND_RESET_I(4);
    vlSelf->__PVT__per_core_valid_out = VL_RAND_RESET_I(4);
    vlSelf->__PVT__per_core_has_fflags = VL_RAND_RESET_I(4);
    vlSelf->__PVT__per_core_fflags = VL_RAND_RESET_I(20);
    vlSelf->__PVT__core_select = VL_RAND_RESET_I(2);
    vlSelf->__PVT__is_fadd = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fsub = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fmul = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fmadd = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fmsub = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fnmadd = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fnmsub = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_div = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_fcmp = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_itof = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_utof = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_ftoi = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_ftou = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_f2f = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dst_fmt = VL_RAND_RESET_I(1);
    vlSelf->__PVT__int_fmt = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<3; ++__Vi0) {
        VL_RAND_RESET_W(256, vlSelf->__PVT__operands[__Vi0]);
    }
    vlSelf->__Vcellout__div_sqrt_arb__ready_in = VL_RAND_RESET_I(2);
    vlSelf->__Vcellinp__div_sqrt_arb__valid_in = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(540, vlSelf->__PVT__per_core_data_out);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fma__DOT__result_fma);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fma__DOT__result_fadd);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fma__DOT__result_fsub);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fma__DOT__result_fmul);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fma__DOT__result_fmadd);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fma__DOT__result_fmsub);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fma__DOT__result_fnmadd);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fma__DOT__result_fnmsub);
    vlSelf->__PVT__fma__DOT__fflags_fma = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fflags_fadd = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fflags_fsub = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fflags_fmul = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fflags_fmadd = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fflags_fmsub = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fflags_fnmadd = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fflags_fnmsub = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fma__DOT__fma_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fma__DOT__fma_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fma__DOT__fma_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fma__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fdiv__DOT__result_fdiv_r);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fdiv__DOT__result_fdiv);
    vlSelf->__PVT__fdiv__DOT__fflags_fdiv = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fdiv__DOT__fdiv_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fdiv__DOT__fdiv_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fdiv__DOT__fdiv_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fdiv__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fsqrt__DOT__result_fsqrt_r);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fsqrt__DOT__result_fsqrt);
    vlSelf->__PVT__fsqrt__DOT__fflags_fsqrt = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fsqrt__DOT__fsqrt_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fsqrt__DOT__fsqrt_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fsqrt__DOT__fsqrt_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fsqrt__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fcvt__DOT__result_fcvt);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fcvt__DOT__result_itof);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fcvt__DOT__result_utof);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fcvt__DOT__result_ftoi);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fcvt__DOT__result_ftou);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fcvt__DOT__result_f2f);
    vlSelf->__PVT__fcvt__DOT__fflags_fcvt = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fcvt__DOT__fflags_itof = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fcvt__DOT__fflags_utof = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fcvt__DOT__fflags_ftoi = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fcvt__DOT__fflags_ftou = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fcvt__DOT__fcvt_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fcvt__DOT__fcvt_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fcvt__DOT__fcvt_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fcvt__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    VL_RAND_RESET_W(128, vlSelf->__PVT__fncp__DOT__result_fncp);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fclss);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_flt);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fle);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_feq);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fmin);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fmax);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fsgnj);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fsgnjn);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fsgnjx);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fmvx);
    VL_RAND_RESET_W(256, vlSelf->__PVT__fncp__DOT__result_fmvf);
    vlSelf->__PVT__fncp__DOT__fflags_fncp = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fncp__DOT__fflags_flt = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fncp__DOT__fflags_fle = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fncp__DOT__fflags_feq = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fncp__DOT__fflags_fmin = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fncp__DOT__fflags_fmax = VL_RAND_RESET_I(20);
    vlSelf->__PVT__fncp__DOT__fncp_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fncp__DOT__fncp_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fncp__DOT__fncp_fire = VL_RAND_RESET_I(1);
    vlSelf->__PVT__fncp__DOT_____05Ffflags_merged = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h41c8a5b5__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hc3f8bfe1__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h49eb26c4__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h147cf4e8__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h71951e49__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h01b131d5__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hacab2bfc__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h198ed5c2__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h8d23a7ba__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h790a2257__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_ha816653d__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h24bf1863__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h8d4e7366__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h6ce28c5f__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h268775a1__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hc8074bd5__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h876b3e60__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_hf8131c8b__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h63cd8b65__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h82db57c2__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h98d9d482__0 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h98d9d482__1 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h98d9d482__2 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h98d9d482__3 = VL_RAND_RESET_I(5);
    vlSelf->__Vlvbound_h98d9d482__4 = VL_RAND_RESET_I(5);
    VL_RAND_RESET_W(135, vlSelf->div_sqrt_arb__DOT____Vxrand_h3a5e75a1__0);
    VL_RAND_RESET_W(136, vlSelf->div_sqrt_arb__DOT____Vcellinp__genblk1__DOT__genblk1__DOT__out_buf__data_in);
    vlSelf->__PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_index_r = VL_RAND_RESET_I(1);
    vlSelf->__PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_onehot_r = VL_RAND_RESET_I(2);
    vlSelf->__PVT__div_sqrt_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__state = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(135, vlSelf->rsp_arb__DOT____Vxrand_h3a5e75a1__0);
    VL_RAND_RESET_W(137, vlSelf->rsp_arb__DOT____Vcellinp__genblk1__DOT__genblk1__DOT__out_buf__data_in);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_index_r = VL_RAND_RESET_I(2);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__grant_onehot_r = VL_RAND_RESET_I(4);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__arbiter__DOT__genblk1__DOT__rr_arbiter__DOT__genblk1__DOT__state = VL_RAND_RESET_I(2);
    VL_RAND_RESET_W(137, vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__data_out_r);
    VL_RAND_RESET_W(137, vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__buffer);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__valid_out_r = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__use_buffer = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__stall_out = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(540, vlSelf->__PVT__fma__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fma__DOT__shift_reg__DOT____Vlvbound_h4cd7645a__0 = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vlvbound_h3fda9eff__0 = VL_RAND_RESET_I(1);
    vlSelf->fma__DOT__shift_reg__DOT____Vlvbound_h51e46508__0 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(2025, vlSelf->__PVT__fdiv__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vlvbound_h790d5d4e__0 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vlvbound_h0c1ea029__0 = VL_RAND_RESET_I(1);
    vlSelf->fdiv__DOT__shift_reg__DOT____Vlvbound_h7e234417__0 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(1350, vlSelf->__PVT__fsqrt__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vlvbound_h2627712a__0 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vlvbound_h94c3c44b__0 = VL_RAND_RESET_I(1);
    vlSelf->fsqrt__DOT__shift_reg__DOT____Vlvbound_hf588c92f__0 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(675, vlSelf->__PVT__fcvt__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vlvbound_h6d835738__0 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vlvbound_h784a533e__0 = VL_RAND_RESET_I(1);
    vlSelf->fcvt__DOT__shift_reg__DOT____Vlvbound_hf606f480__0 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__1 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vxrand_h9b58951b__0 = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(272, vlSelf->__PVT__fncp__DOT__shift_reg__DOT__genblk1__DOT__entries);
    vlSelf->fncp__DOT__shift_reg__DOT____Vlvbound_hb3b562d1__0 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vlvbound_h0fa13e82__0 = VL_RAND_RESET_I(1);
    vlSelf->fncp__DOT__shift_reg__DOT____Vlvbound_hba509cd1__0 = VL_RAND_RESET_I(1);
    vlSelf->__Vtask_dpi_fadd__0__result = 0;
    vlSelf->__Vtask_dpi_fadd__0__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__1__result = 0;
    vlSelf->__Vtask_dpi_fsub__1__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__2__result = 0;
    vlSelf->__Vtask_dpi_fmul__2__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__3__result = 0;
    vlSelf->__Vtask_dpi_fmadd__3__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__4__result = 0;
    vlSelf->__Vtask_dpi_fmsub__4__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__5__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__5__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__6__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__6__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__7__result = 0;
    vlSelf->__Vtask_dpi_fdiv__7__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__8__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__8__fflags = 0;
    vlSelf->__Vtask_dpi_itof__9__result = 0;
    vlSelf->__Vtask_dpi_itof__9__fflags = 0;
    vlSelf->__Vtask_dpi_utof__10__result = 0;
    vlSelf->__Vtask_dpi_utof__10__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__11__result = 0;
    vlSelf->__Vtask_dpi_ftoi__11__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__12__result = 0;
    vlSelf->__Vtask_dpi_ftou__12__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__13__result = 0;
    vlSelf->__Vtask_dpi_fclss__14__result = 0;
    vlSelf->__Vtask_dpi_fle__15__result = 0;
    vlSelf->__Vtask_dpi_fle__15__fflags = 0;
    vlSelf->__Vtask_dpi_flt__16__result = 0;
    vlSelf->__Vtask_dpi_flt__16__fflags = 0;
    vlSelf->__Vtask_dpi_feq__17__result = 0;
    vlSelf->__Vtask_dpi_feq__17__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__18__result = 0;
    vlSelf->__Vtask_dpi_fmin__18__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__19__result = 0;
    vlSelf->__Vtask_dpi_fmax__19__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__20__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__21__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__22__result = 0;
    vlSelf->__Vtask_dpi_fadd__23__result = 0;
    vlSelf->__Vtask_dpi_fadd__23__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__24__result = 0;
    vlSelf->__Vtask_dpi_fsub__24__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__25__result = 0;
    vlSelf->__Vtask_dpi_fmul__25__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__26__result = 0;
    vlSelf->__Vtask_dpi_fmadd__26__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__27__result = 0;
    vlSelf->__Vtask_dpi_fmsub__27__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__28__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__28__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__29__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__29__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__30__result = 0;
    vlSelf->__Vtask_dpi_fdiv__30__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__31__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__31__fflags = 0;
    vlSelf->__Vtask_dpi_itof__32__result = 0;
    vlSelf->__Vtask_dpi_itof__32__fflags = 0;
    vlSelf->__Vtask_dpi_utof__33__result = 0;
    vlSelf->__Vtask_dpi_utof__33__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__34__result = 0;
    vlSelf->__Vtask_dpi_ftoi__34__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__35__result = 0;
    vlSelf->__Vtask_dpi_ftou__35__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__36__result = 0;
    vlSelf->__Vtask_dpi_fclss__37__result = 0;
    vlSelf->__Vtask_dpi_fle__38__result = 0;
    vlSelf->__Vtask_dpi_fle__38__fflags = 0;
    vlSelf->__Vtask_dpi_flt__39__result = 0;
    vlSelf->__Vtask_dpi_flt__39__fflags = 0;
    vlSelf->__Vtask_dpi_feq__40__result = 0;
    vlSelf->__Vtask_dpi_feq__40__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__41__result = 0;
    vlSelf->__Vtask_dpi_fmin__41__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__42__result = 0;
    vlSelf->__Vtask_dpi_fmax__42__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__43__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__44__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__45__result = 0;
    vlSelf->__Vtask_dpi_fadd__46__result = 0;
    vlSelf->__Vtask_dpi_fadd__46__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__47__result = 0;
    vlSelf->__Vtask_dpi_fsub__47__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__48__result = 0;
    vlSelf->__Vtask_dpi_fmul__48__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__49__result = 0;
    vlSelf->__Vtask_dpi_fmadd__49__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__50__result = 0;
    vlSelf->__Vtask_dpi_fmsub__50__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__51__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__51__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__52__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__52__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__53__result = 0;
    vlSelf->__Vtask_dpi_fdiv__53__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__54__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__54__fflags = 0;
    vlSelf->__Vtask_dpi_itof__55__result = 0;
    vlSelf->__Vtask_dpi_itof__55__fflags = 0;
    vlSelf->__Vtask_dpi_utof__56__result = 0;
    vlSelf->__Vtask_dpi_utof__56__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__57__result = 0;
    vlSelf->__Vtask_dpi_ftoi__57__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__58__result = 0;
    vlSelf->__Vtask_dpi_ftou__58__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__59__result = 0;
    vlSelf->__Vtask_dpi_fclss__60__result = 0;
    vlSelf->__Vtask_dpi_fle__61__result = 0;
    vlSelf->__Vtask_dpi_fle__61__fflags = 0;
    vlSelf->__Vtask_dpi_flt__62__result = 0;
    vlSelf->__Vtask_dpi_flt__62__fflags = 0;
    vlSelf->__Vtask_dpi_feq__63__result = 0;
    vlSelf->__Vtask_dpi_feq__63__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__64__result = 0;
    vlSelf->__Vtask_dpi_fmin__64__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__65__result = 0;
    vlSelf->__Vtask_dpi_fmax__65__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__66__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__67__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__68__result = 0;
    vlSelf->__Vtask_dpi_fadd__69__result = 0;
    vlSelf->__Vtask_dpi_fadd__69__fflags = 0;
    vlSelf->__Vtask_dpi_fsub__70__result = 0;
    vlSelf->__Vtask_dpi_fsub__70__fflags = 0;
    vlSelf->__Vtask_dpi_fmul__71__result = 0;
    vlSelf->__Vtask_dpi_fmul__71__fflags = 0;
    vlSelf->__Vtask_dpi_fmadd__72__result = 0;
    vlSelf->__Vtask_dpi_fmadd__72__fflags = 0;
    vlSelf->__Vtask_dpi_fmsub__73__result = 0;
    vlSelf->__Vtask_dpi_fmsub__73__fflags = 0;
    vlSelf->__Vtask_dpi_fnmadd__74__result = 0;
    vlSelf->__Vtask_dpi_fnmadd__74__fflags = 0;
    vlSelf->__Vtask_dpi_fnmsub__75__result = 0;
    vlSelf->__Vtask_dpi_fnmsub__75__fflags = 0;
    vlSelf->__Vtask_dpi_fdiv__76__result = 0;
    vlSelf->__Vtask_dpi_fdiv__76__fflags = 0;
    vlSelf->__Vtask_dpi_fsqrt__77__result = 0;
    vlSelf->__Vtask_dpi_fsqrt__77__fflags = 0;
    vlSelf->__Vtask_dpi_itof__78__result = 0;
    vlSelf->__Vtask_dpi_itof__78__fflags = 0;
    vlSelf->__Vtask_dpi_utof__79__result = 0;
    vlSelf->__Vtask_dpi_utof__79__fflags = 0;
    vlSelf->__Vtask_dpi_ftoi__80__result = 0;
    vlSelf->__Vtask_dpi_ftoi__80__fflags = 0;
    vlSelf->__Vtask_dpi_ftou__81__result = 0;
    vlSelf->__Vtask_dpi_ftou__81__fflags = 0;
    vlSelf->__Vtask_dpi_f2f__82__result = 0;
    vlSelf->__Vtask_dpi_fclss__83__result = 0;
    vlSelf->__Vtask_dpi_fle__84__result = 0;
    vlSelf->__Vtask_dpi_fle__84__fflags = 0;
    vlSelf->__Vtask_dpi_flt__85__result = 0;
    vlSelf->__Vtask_dpi_flt__85__fflags = 0;
    vlSelf->__Vtask_dpi_feq__86__result = 0;
    vlSelf->__Vtask_dpi_feq__86__fflags = 0;
    vlSelf->__Vtask_dpi_fmin__87__result = 0;
    vlSelf->__Vtask_dpi_fmin__87__fflags = 0;
    vlSelf->__Vtask_dpi_fmax__88__result = 0;
    vlSelf->__Vtask_dpi_fmax__88__fflags = 0;
    vlSelf->__Vtask_dpi_fsgnj__89__result = 0;
    vlSelf->__Vtask_dpi_fsgnjn__90__result = 0;
    vlSelf->__Vtask_dpi_fsgnjx__91__result = 0;
    vlSelf->__Vtableidx1 = 0;
    vlSelf->__Vtableidx2 = 0;
    vlSelf->__Vtableidx3 = 0;
    vlSelf->__Vtableidx4 = 0;
    vlSelf->__Vtableidx5 = 0;
    vlSelf->__Vtableidx6 = 0;
    vlSelf->__Vtableidx7 = 0;
    vlSelf->__Vtableidx8 = 0;
    vlSelf->__Vdly__rsp_arb__DOT__genblk1__DOT__genblk1__DOT__out_buf__DOT__genblk1__DOT__skid_buffer__DOT__genblk1__DOT__stream_buffer__DOT__genblk1__DOT__genblk1__DOT__valid_out_r = VL_RAND_RESET_I(1);
}
